global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Linq;
global using System.Windows;
global using System.Windows.Input;
global using System.Windows.Controls;

global using BookManagement.Helpers;
global using BookManagement.Models.Entities;
global using BookManagement.Models.DTOs;
global using BookManagement.ViewModels.Common;
global using BookManagement.ViewModels.Reader;
global using BookManagement.ViewModels.Author;
global using BookManagement.ViewModels.Admin;
global using BookManagement.Services.Navigation;
global using BookManagement.Services.Repository;
global using BookManagement.Services.Mock;
global using BookManagement.Services.Notification;
global using BookManagement.Services.Dialog;
global using BookManagement.Converters;
global using BookManagement.Views.Common;
global using BookManagement.Views.Reader;
global using BookManagement.Views.Author;
global using BookManagement.Views.Admin;
global using RelayCommand = BookManagement.Helpers.RelayCommand;
